name: CI

on:
  push:
    tags:
      - 'v**'

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup base-image
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8
      - name: chmod build
        run: chmod +x gradlew
      - name: build
        run: ./gradlew clean build --exclude-task test
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker Image build&push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: johnpark0921/morning-bear:${{ github.ref_name }}